### ISSUE TITLE
Why does data/user.yml seem to want a secret key?

### ISSUE THREAD

**Issue by BeastOfBodmin** [ryan-shaw/binance-order-bot#1]
```
### Copy this file to user.yml

binance:
  api_key: api key here
  api_secret_key: api secret here
```
